=== Shimaa-Ibrahim/labs/librarySchema/src/libraryschema/libraryXmlSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="library" type= "libraryType"/>

    <xs:complexType name="libraryType">
        <xs:sequence>
            <xs:element name="librarian" type = "xs:string" maxOccurs="unbounded"/>
            <xs:element name = "book" type ="bookType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="location" type="xs:string" use="required"/>
        <xs:attribute name="description" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name ="bookType">
        <xs:sequence>
            <xs:element name = "auther" type="xs:string"/>
            <xs:element name = "preface" type="xs:string"/>
            <xs:element name = "part" type="partType"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="ISBN" type="xs:int" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="partType">
        <xs:sequence>
            <xs:element name = "chapter" type="chapterType" maxOccurs = "unbounded"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="chapterType">
        <xs:sequence>
            <xs:element name="section" type ="sectionType" maxOccurs = "unbounded"/>
            <xs:element name="summary" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="sectionType">
        <xs:sequence>
            <xs:element name="paragraph" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Shimaa-Ibrahim/labs/librarySchema/src/libraryschema/librarySchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="libraryXmlSchema.xsd" 
     location = "aaaaa " description = "aaaaaaaa ">
    <librarian></librarian>
    <librarian></librarian>

    <book title = "aaaaaaaa " ISBN = "123">
        <auther>aaaaaaaaaaa</auther>

        <preface>aaaaaaaaaaaa</preface>

        <part title = "aaaaaaaa ">
            <chapter title = "aaaaaaaaaaaa">
                <section>
                    <paragraph>aaaaaaaaaaaa</paragraph>
                </section>
                
                <section>
                    <paragraph>aaaaaaaaaaaa</paragraph>
                </section>
                <section>
                    <paragraph>aaaaaaaaaaaa</paragraph>
                </section>
                <summary>aaaaaaaaaaaaaaa</summary>

            </chapter>
        </part>
    </book> 
    
</library>
