=== Shimaa-Ibrahim/labs/XML lab1/src/XMLDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT library (librarian+,book+)>
<!ATTLIST library 
        location ID #REQUIRED
        description CDATA "library">


<!ELEMENT librarian (#PCDATA)>

<!ELEMENT book (auther+,preface,part+)>
<!ATTLIST book 
        title ID #REQUIRED
        ISBN NMTOKEN #REQUIRED>

<!ELEMENT auther (#PCDATA)>
<!ELEMENT preface (#PCDATA)>

<!ELEMENT part (chapter+)>
<!ATTLIST part 
        title CDATA #REQUIRED>

<!ELEMENT chapter (section+ ,summary)>
<!ATTLIST chapter 
        title CDATA #REQUIRED>


<!ELEMENT section (paragraph+)>
<!ATTLIST part 
        title CDATA #REQUIRED>

<!ELEMENT summary (#PCDATA)>

<!ELEMENT paragraph (#PCDATA)>

=== Shimaa-Ibrahim/labs/XML lab1/src/XMLLab1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE liberary SYSTEM "XMLDTD.dtd">
<library location = "aaaaa " description = "aaaaaaaa ">
    <librarian></librarian>
    <librarian></librarian>

    <book title = "aaaaaaaa " ISBN = "aaaaaaaaaa ">
        <auther>aaaaaaaaaaa</auther>

        <preface>aaaaaaaaaaaa</preface>

        <part title = "aaaaaaaa ">
            <chapter title = "aaaaaaaaaaaa">
                <section>
                    <paragraph>aaaaaaaaaaaa</paragraph>
                </section>
                
                <section>
                    <paragraph>aaaaaaaaaaaa</paragraph>
                </section>
                <section>
                    <paragraph>aaaaaaaaaaaa</paragraph>
                </section>
                <summary>aaaaaaaaaaaaaaa</summary>

            </chapter>
        </part>
    </book> 
    
</library>
